services:
  caddy:
    image: caddy:2.9-alpine@sha256:b4e3952384eb9524a887633ce65c752dd7c71314d2c2acf98cd5c715aaa534f0
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  n8n:
    image: n8nio/n8n:1.84.3@sha256:32958c20b771afbfa467fa3fda3ac618164436e69dece9ae29989e69a3e35c89
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

# Create the volumes with `docker volume create <volume_name>`
volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  n8n_data:
    external: true
