services:
  caddy:
    image: caddy:2.11-alpine
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    mem_limit: 30m
    mem_reservation: 20m
    memswap_limit: 40m
    oom_score_adj: -200

  n8n:
    image: n8nio/n8n:2.30.5
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          'wget -q -O - http://0.0.0.0:5678/healthz | grep -qF ''"status":"ok"'' || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 480s
    mem_limit: 600m
    mem_reservation: 440m
    memswap_limit: 740m
    oom_score_adj: 100

  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 16m
    mem_reservation: 10m
    memswap_limit: 20m
    oom_score_adj: -200

# Create the volumes with `docker volume create <volume_name>`
volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  n8n_data:
    external: true
